Add line recognition
SixLabors/Fonts pull request #246
Opened 2022-02-24 23:29 UTC by steffi3011

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/Fonts/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [ ] I have provided test coverage for my change (where applicable)

### Description

Add line recognition to determine the number of rows needed in the generated layout.

2022-02-24 23:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SixLabors/Fonts?pullRequest=246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SixLabors/Fonts?pullRequest=246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SixLabors/Fonts?pullRequest=246) it.</sub>

2022-02-25 07:44 UTC, JimBobSquarePants requested changes
Thanks for this submission @steffi3011 I really appreciate the assistance. 

It looks like we're missing unit tests plus there's some StyleCop issues. I've also provided suggestion for the intellisense documentation. 

Please let me know if you need help with anything.

2022-02-25 07:44 UTC, JimBobSquarePants commented on src/SixLabors.Fonts/TextMeasurer.cs
> +        /// <returns>The count of lines used.</returns>
```suggestion
        /// <summary>
        /// Gets the number of lines contained within the text.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <param name="options">The style.</param>
        /// <returns>The line count.</returns>
```

2022-02-25 07:44 UTC, JimBobSquarePants commented on src/SixLabors.Fonts/TextMeasurer.cs
> +        /// <returns>The count of lines used.</returns>
```suggestion
```suggestion
        /// <summary>
        /// Gets the number of lines contained within the text.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <param name="options">The style.</param>
        /// <returns>The line count.</returns>
```
```

2022-02-26 01:19 UTC, JimBobSquarePants approved these changes
Fantastic, thanks for your help 👍

2022-02-26 01:19 UTC, merged

2022-03-07 08:19 UTC, steffi3011 commented
You are welcome.
Could you tell me when a new version with this feature will be released?

2022-03-07 08:34 UTC, JimBobSquarePants commented
It’s available in our MyGet feed now. We don’t have a timeframe for the next NuGet release

2022-03-09 12:41 UTC, steffi3011 commented
For us, this new version with this special feature would be very important. Maybe it is possible to make the NuGet release as soon as possible?

2022-03-09 15:45 UTC, JimBobSquarePants commented
@steffi3011 Does your company have a [SixLabors License](https://sixlabors.com/pricing/)?