Add exposed function to retrieve all unicode codepoints defined in fonts
SixLabors/Fonts pull request #308
Opened 2022-11-23 08:47 UTC by CptWesley

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/Fonts/pulls) open
- [X] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [X] I have provided test coverage for my change (where applicable)

### Description

Fixes #307

As described in the suggestion, exposing this information can make it easier for users to retrieve some extra information about what code points and glyphs are available in a font and how they are being mapped.

Changes:
- Added `GetAvailableCodePoints` function to `Font` type which retrieves all defined code points in that particular font.
- Made `GlyphId` field in `GlyphMetrics` public.

2022-11-23 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SixLabors/Fonts?pullRequest=308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SixLabors/Fonts?pullRequest=308) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SixLabors/Fonts?pullRequest=308) it.</sub>

2022-11-23 11:52 UTC, JimBobSquarePants requested changes
Hi there. Thanks for making an effort here. This looks pretty good!

I think we should implement a few performance tweaks though and I'm unsure about the expected behavior.

2022-11-23 11:52 UTC, JimBobSquarePants commented on src/SixLabors.Fonts/Font.cs
> +        public IEnumerable<CodePoint> GetAvailableCodePoints()
This should probably be IReadOnlyCollection<CodePoint> since we want it to be a one-time enumeration.

2022-11-23 11:52 UTC, JimBobSquarePants commented on tests/SixLabors.Fonts.Tests/FontCodePointsTests.cs
> +            FontFamily family = collection.Add(TestFonts.SimpleFontFile);
I think we should run these tests using a real font.

2022-11-23 11:52 UTC, JimBobSquarePants commented on src/SixLabors.Fonts/Tables/General/CMap/Format14SubTable.cs
> +            => Array.Empty<int>();
Shouldn't we return the variationSelectors keys here?

2022-12-20 11:41 UTC, JimBobSquarePants commented
I haven't forgotten about this. I'm just doing some research to ensure we can implement the correct thing.

2023-01-14 18:53 UTC, CptWesley commented
My apologies for no longer replying due to the holiday season. I have not incorporated the requested changes due to the fact that it seems this might not be the right approach for solving this due to what you mentioned and what was mentioned in #307. My personal experience with font rendering is very minimal, so I'm not sure what the right approach would be, but if I can be of any help, please let me know.

2023-03-08 09:50 UTC, JimBobSquarePants commented
Hi @CptWesley I did some research, and I cannot find a definitive answer regarding variations. As such I believe it's best to leave as-is. 

The rest of your code is ace. All I changed was the review comments re optimization. Thanks!

2023-03-08 09:50 UTC, JimBobSquarePants approved these changes

2023-03-08 09:50 UTC, merged

2023-03-08 18:06 UTC, CptWesley commented
@JimBobSquarePants Thank you very much!